### ISSUE TITLE
[Enhancement] Mercury Web Parser API

### ISSUE THREAD

**Issue by Yukaii** [zetavg/moerss#1]
https://mercury.postlight.com/web-parser/

不知道生 feed 速度會不會降低就是了 😅

**Comment by zetavg** [comment]
其實我已經用了，只是還沒 push 上來 www

不過後來發現在大部分的情況，`read` 給的結果都不遜於 Mercury，甚至更加準確。所以後來乾脆[兩個都用然後取其優](https://github.com/zetavg/Feedify/blob/14cc83c1f1eb615a0e3ac171045f9695858adbbf/src/page-processors/PageProcessor.js#L105-L145)了。
